application: whereamiriding
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration: 10000d

# Most bots request robots
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
  expiration: 10000d

- url: /cache/(.*)
  script: datacache.cache\1_app
  login: admin

- url: /prefs/(.*)
  script: prefs.prefs_app

- url: /riderhistory/(.*)
  script: riderhistory.riderhistory_app

- url: /eventinfo/(.*)
  script: eventinfo.eventinfo_app

- url: /register/
  script: registration.registration_app

- url: /.*
  script: main.app
