application: whereamiriding
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration: 10000d

# Most bots request robots
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
  expiration: 10000d

- url: /.*
  script: dynmap.app
